<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="scp.targets.mock.RequesterResponderTest" tests="8" skipped="0" failures="0" errors="0" timestamp="2015-12-05T01:29:22" hostname="DESKTOP-PE2SLM5" time="1.032">
  <properties/>
  <testcase name="testExcessLoad" classname="scp.targets.mock.RequesterResponderTest" time="0.252"/>
  <testcase name="testRemoteUnknownFailure" classname="scp.targets.mock.RequesterResponderTest" time="0.141"/>
  <testcase name="testLocalTimeOut" classname="scp.targets.mock.RequesterResponderTest" time="0.013"/>
  <testcase name="testStaleData" classname="scp.targets.mock.RequesterResponderTest" time="0.127"/>
  <testcase name="testDataUnavailable" classname="scp.targets.mock.RequesterResponderTest" time="0.125"/>
  <testcase name="testSuccessfulRequest" classname="scp.targets.mock.RequesterResponderTest" time="0.125"/>
  <testcase name="testFastRequest" classname="scp.targets.mock.RequesterResponderTest" time="0.124"/>
  <testcase name="testRemoteTimeOut" classname="scp.targets.mock.RequesterResponderTest" time="0.125"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[[pool-91-thread-1] WARN scp.impl.ResponderInvoker - Dropping 2-th reception
[pool-91-thread-1] ERROR scp.impl.ResponderInvoker - Failed to handle 1-th reception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at scp.impl.ResponderInvoker.invokeHandler(ResponderInvoker.java:100)
	at scp.impl.ResponderInvoker.serviceRequest(ResponderInvoker.java:87)
	at scp.targets.mock.InProcessCommunicationManagerImpl$3.lambda$request$10(InProcessCommunicationManagerImpl.java:125)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at scp.api.RequesterResponderTest$3.respond(RequesterResponderTest.java:163)
	... 4 more
[Test worker] WARN scp.impl.RequestRequester - Timed out handling 1-th request
[Test worker] INFO scp.impl.RequestRequester - Handling stale 1-th response
[Test worker] INFO scp.impl.RequestRequester - Handling stale 1-th response
[Test worker] WARN scp.impl.RequestRequester - Dropping 2-th request
[pool-91-thread-1] WARN scp.impl.ResponderInvoker - Timed out handling 1-th reception
]]></system-err>
</testsuite>
