<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="scp.targets.dds.SenderReceiverTest" tests="7" skipped="1" failures="0" errors="0" timestamp="2015-12-05T01:28:39" hostname="DESKTOP-PE2SLM5" time="23.594">
  <properties/>
  <testcase name="testExcessLoad" classname="scp.targets.dds.SenderReceiverTest" time="3.469"/>
  <testcase name="testRemoteUnknownFailure" classname="scp.targets.dds.SenderReceiverTest" time="3.438"/>
  <testcase name="testLocalTimeOut" classname="scp.targets.dds.SenderReceiverTest" time="3.422">
    <skipped/>
  </testcase>
  <testcase name="testDataAccepted" classname="scp.targets.dds.SenderReceiverTest" time="3.422"/>
  <testcase name="testRemoteTimeOut" classname="scp.targets.dds.SenderReceiverTest" time="3.593"/>
  <testcase name="testFastSend" classname="scp.targets.dds.SenderReceiverTest" time="3.828"/>
  <testcase name="testDataRejected" classname="scp.targets.dds.SenderReceiverTest" time="2.422"/>
  <system-out><![CDATA[Exception was thrown while processing request
]]></system-out>
  <system-err><![CDATA[com.rti.dds.infrastructure.RETCODE_BAD_PARAMETER: Invalid related request identity (sequence number is SequenceNumber_t[high=-1, low=4294967295]
	at com.rti.connext.requestreply.Replier.getWriteParamsForRelatedRequest(Unknown Source)
	at com.rti.connext.requestreply.Replier.sendReply(Unknown Source)
	at com.rti.connext.requestreply.SimpleReplier$ReplierListenerAdapter.onRequestAvailable(Unknown Source)
	at com.rti.connext.requestreply.Replier$ReplierDataReaderListener.on_data_available(Unknown Source)
	at com.rti.dds.subscription.DataReaderListenerImpl.on_data_available(Unknown Source)
[Thread-200] WARN scp.impl.ReceiverInvoker - Dropping 2-th reception
[Thread-207] ERROR scp.impl.ReceiverInvoker - Failed to handle 1-th reception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at scp.impl.ReceiverInvoker.invokeHandler(ReceiverInvoker.java:99)
	at scp.impl.ReceiverInvoker.receive(ReceiverInvoker.java:86)
	at scp.targets.dds.CommunicationManagerImpl$2.invoke(CommunicationManagerImpl.java:259)
	at scp.targets.dds.CommunicationManagerImpl$2.invoke(CommunicationManagerImpl.java:255)
	at scp.targets.dds.RequestReplyBasedGeneralServerRequestHandler.onRequestAvailable(RequestReplyBasedGeneralServerRequestHandler.java:61)
	at scp.targets.dds.RequestReplyBasedGeneralServerRequestHandler.onRequestAvailable(RequestReplyBasedGeneralServerRequestHandler.java:27)
	at com.rti.connext.requestreply.SimpleReplier$ReplierListenerAdapter.onRequestAvailable(Unknown Source)
	at com.rti.connext.requestreply.Replier$ReplierDataReaderListener.on_data_available(Unknown Source)
	at com.rti.dds.subscription.DataReaderListenerImpl.on_data_available(Unknown Source)
Caused by: java.lang.RuntimeException: Don't Panic! This exception is good :)
	at scp.api.SenderReceiverTest$3.receive(SenderReceiverTest.java:146)
	at scp.api.SenderReceiverTest$3.receive(SenderReceiverTest.java:143)
	at scp.impl.ReceiverInvoker.lambda$invokeHandler$3(ReceiverInvoker.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[Thread-229] WARN scp.impl.ReceiverInvoker - Timed out handling 1-th reception
[Test worker] WARN scp.impl.SendRequester - Timed out handling 1-th send
[Test worker] WARN scp.impl.SendRequester - Dropping 2-th send
]]></system-err>
</testsuite>
